# General settings
name: 'EDGES'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use full path
check_val_every_n_epochs: 50
sample_every_val: 4
val_check_interval: null
samples_to_generate: 10       # We advise to set it to 2 x batch_size maximum
samples_to_save: 10

log_every_steps: 50
