# Training settings
n_epochs: 1000
# batch_size: 32  moved to dataset configs 
lr: 0.001
clip_grad: null          # float, null to disable
save_model: False
num_workers: 8
ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
progress_bar: false
weight_decay: 1e-12
optimizer: adam 
amsgrad: true
overfit: false
seed: 0
